java_binary(
  name = 'di_example',
  srcs = glob(['*.java']),
  main_class = 'diexample.DiExample',
  deps = [
    '@maven//:org_springframework_spring_context',
    '@maven//:org_springframework_spring_beans',
  ],
)
