FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y cmake ninja-build
RUN apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv \
ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
