[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"
