[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = "1.0.215"
serde_json = "1.0.133"
