version: '3'

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    ports:
      - "80:80" # The HTTP port
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yaml
      - ./conf.yml:/etc/traefik/conf.yml

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
