java_binary(
  name = 'demo',
  srcs = glob(['*.java']),
  main_class = 'demo.PodLister',
  deps = [
    '@maven//:io_fabric8_kubernetes_client',
    '@maven//:io_fabric8_kubernetes_client_api'
  ],
)
