java_binary(
  name = 'demo',
  srcs = glob(['*.java']),
  main_class = 'demo.InformerSample',
  deps = [
    '@maven//:io_fabric8_kubernetes_client',
    '@maven//:io_fabric8_kubernetes_client_api',
    '@maven//:io_fabric8_kubernetes_model_core'
  ],
)
