[package]
name = "parallel-http-requests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12" }
tokio = { version = "1", features = ["full"] }
