version: '3'
services:
  web:
    build: ./web
    container_name: web
    ports:
      - 8080:80
    volumes:
      - "./web/public-html:/usr/local/apache2/htdocs/"

  api:
    build: ./api
    container_name: api
    ports:
      - 5000:5000
    volumes:
      - "./api:/app"
    environment:
      PYTHONUNBUFFERED: 'true'

networks:
  default:
    name: kafka_net
    external: true
